spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: admin
    password: aass6759
    url: jdbc:mysql://caterplanner.cdkfvcl3aw1z.us-east-2.rds.amazonaws.com/CaterPlanner
  jpa:
    hibernate:
      ddl-auto: update

cloud:
  aws:
      credentials:
        accessKey: AKIAJGHYRH3VM3Q47OBA
        secretKey: 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
      s3:
        bucket: caterplanner
      region:
        static: ap-northeast-2
      stack:
        auto: false

server:
  port: 5252

